#═══════[ CORE CONFIG ]═══════✧#
SESSION_ID='BWM-XMD;;;H4sIAAAAAAAAA71V266jNhT9lcqviSbcIZGONIYAuV/J7VR9cMAQE24xJoSM8i196Vt/rp9QkeR0Rprp6alUFQnJGNhea3mt7S8gSUmOh7gCnS8go+SMGK6HrMow6AC98H1MQRN4iCHQAauhoBmUa/Wrkjus7V0YDDQqXOfhSDEdRjE1jnTklCM7Sl/ArQmyYh8R952Cx8PFrTw3qryizKbtcNDwsE18Iu84O5seC4WPIr0Pr6P16gXc6oqIUJIEZnbAMaYoGuJqhgj9GPxy6rzqhX894OrV2Y7LM8dfF+P9Xp62nEIL8vmcZK11ueltVx+D309YRhqL8uoo0xkyE+1Vl0XDeIVkFJcXW1PZse84IdXt8QN+ToIEe30PJ4yw6sO6x3rlXkfHfqpW/lGe2PP02pi2kAFLrjritDHzpGI9DiJjk38MuDtYxpEkOL2VFJP1oNTpiltsudAdbcdQQ1M4CduGdeXbevAt8Bl988rx3+g+7kNvL7LTZrEaHcTByfXsOGyUujUsynbgFtzlrMHG1FyuPmibyzooFbGrZMZk5Mdj02TKZHBsa90Uq85r1tCW5sqviDeqVl/hI1bQ91BKvVfID83Lbujudw14VScOvIgXi/R2+VIo1lw00obhZZVeF4MjminR9iLtZzNJbFtrvZFuJ+LM3OcWdI/bMd2shHO19GH5cmd0xFXfAx3+1gQUByRnFDGSJve5JkDeeYlditldXFAWw1gOD6f42I4UfU2WgT/FukjMdgz9jM33cGH392GZnfsvoAkymro4z7HXIzlLaTXGeY4CnIPOz/d9qilTHKcMD4gHOkBQRJWXeVGTJelz/qk8IJajLPuUYAaawKdpPMagw2iBm+D+g6UKXVUWFM4yOJU3ZIWzJE2TLKENNVlXlJpg/FjUITHOGYoz0OFVWVJVWdGUW/O/wdE2VYMXoCRqlmVCqBlQ7nKmCLmuJAm6wf1fOAyeaytWt80poqB1JZPvQhEqCm9CUxM11XoXh8prt1+aIMEX9khT7QGRbwKf0JytkiKLUuS9Re3tJXLdtEjYskpcox5g+jDOcxozRpIgr5kVCaLugZyxUfMAHR9FOf7Ldphi743Ls5UaqVenYW7rk+FGHYEae13oO206wvfqRI+vZKWtaIIkq5ygSkJH+FzPN0GC6lJgSJLgp6n/k55W+R+//vb7213r9GRQL+hhhkiU1wLPkm2ez21ztoGiNrdt2A+gEUDwlfFbnh+JCc/h67Ql5XiCqvBcNpTx4nQ2qqPjDVMTGRYUqOFalar24MsPitTh57eJPNxHA2s5qw7ceZVs1w1JQEPDEdlqxrzTyZ2OltImiE0rntl4H8F0aec7e4iEPE34xIv3q9Z2BxXLWuStycaZGHX4m8DDZ+LibxczCR1dkU42fcPKxBIvX+VuZjrecrjzK8aRbTTvb4/WtSWLfE+wzaW2asgnHM7OF70lOqGpGIco3xubYLj22+uJpcrn7rPT3Dtd9DxhyLMLkPujT/C9YT+35Z/29oG7diB3a35T4nkC/E0X1XeqJDjnxqgXbvJU1WZFaCJa5pkpLk+6HRzmk1OZ6G7RuJTgVkchixDzUxqDDkCJR9O7dWha1JbuJ376zmIG7PcN+CAeoZzBrzH5QQdQtcdXM5pmPZQfag1sCcZF7fkKZtmSIfaWOgDry5QccPsTbjlabCYJAAA='
PREFIX="."
PUBLIC_MODE='yes'

#═══════[ OWNER DETAILS ]═══════✧#
OWNER_NAME="bright"
OWNER_NUMBER=""

#═══════[ BOT PROFILE ]═══════✧#
BOT_NAME="BWM-XMD"
BOT_IMAGE=""
STARTING_BOT_MESSAGE='yes'

#═══════[ PRESENCE & AUTOMATION ]═══════✧#
PRESENCE='2'
AUTO_READ="no"
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"

#═══════[ CHAT FEATURES ]═══════✧#
CHATBOT="no"
AUDIO_CHATBOT="no"

#═══════[ GROUP SECURITY ]═══════✧#
GROUPANTILINK_REMOVE="no"
ANTIDELETE_SENT_INBOX="yes"
ANTIDELETE_RECOVER_CONVENTION="no"

#═══════[ MESSAGE HANDLING ]═══════✧#
STATUS_REACT_EMOJIS="🚀,🌎"
AUTO_REACT="no"
WELCOME_MESSAGE="no"
GOODBYE_MESSAGE="no"

#═══════[ HEROKU CONFIG ]═══════✧#
HEROKU_APP_NAME=
HEROKU_API_KEY=

#═══════[ AUTO REACTIONS ]═══════✧#
AUTO_REACT_STATUS="yes"
AUTO_REPLY_STATUS="no"
AUTO_REJECT_CALL="no"
AUTO_BIO="no"

#═══════[ MENU DESIGN CONFIG ]═══════✧#
MENU_TOP_LEFT="┌─❖"
MENU_BOT_NAME_LINE="│ "
MENU_BOTTOM_LEFT="└┬❖"
MENU_GREETING_LINE="┌┤ "
MENU_DIVIDER="│└────────┈⳹"
MENU_USER_LINE="│🕵️ "
MENU_DATE_LINE="│📅 "
MENU_TIME_LINE="│⏰ "
MENU_STATS_LINE="│⭐ "
MENU_BOTTOM_DIVIDER="└─────────────┈⳹"
